
discord:
  botkey: "botkey"
  channel: "724287579519713280"
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.lusternia.com"

database:
  connection: "user=ada password=ada dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
